version: '3'

services:
  php:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password123    # Passwort f端r den MySQL-Root-Benutzer
      MYSQL_DATABASE: merkliste           # Name der Datenbank
      MYSQL_USER: user                    # Benutzername f端r die Datenbank
      MYSQL_PASSWORD: password123         # Passwort f端r den MySQL-Benutzer
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql             # Verzeichnis f端r Datenbankdateien
